#!/bin/bash

# add_team_config -- Team-specific configuration
#
# 1. Updates Runtime on the robot.
# 2. Deploys team-specific network configuration.

source "$(git rev-parse --show-toplevel)/DevOps/frankfurter/scripts/tools/env"

deploy_update
make_team_net
