#!/bin/bash

source $(git rev-parse --show-toplevel)/DevOps/frankfurter/scripts/tools/env.sh
./run-remote -q -u debian prepare-logs
scp $ssh_flags "debian@$default_ip:/tmp/*-logs.tar.gz" . 2>/dev/null
ssh $ssh_flags "debian@$default_ip" "rm -rf /tmp/*-logs.tar.gz && rm -rf /tmp/*-logs" 2>/dev/null
