#!/bin/bash

# get_logs -- Downloads Beaglebone systemd logs and code for debugging.

source "$(git rev-parse --show-toplevel)/DevOps/frankfurter/scripts/tools/env"
./run_remote -q prepare-logs
scp $ssh_options "$user@$default_ip:/tmp/*-logs.tar.gz" . 2>/dev/null
ssh $ssh_options "$user@$default_ip" "rm -rf /tmp/*-logs.tar.gz && rm -rf /tmp/*-logs" 2>/dev/null
