#!/bin/bash

today="$(date +%Y-%m-%d)"
build_dir="/tmp/$today-logs"
mkdir "$build_dir"

# Copy system and service logs
dmesg > "$build_dir/dmesg"
journalctl --all -u networking.service > "$build_dir/networking.service.log"
journalctl --all -u runtime.service > "$build_dir/runtime.service.log"
journalctl --all -u update.service > "$build_dir/update.service.log"

# Copy runtime and student code for debugging purposes
cp -r "/home/$USER" "$build_dir/home-dir"

# Copy networking configuration
mkdir "$build_dir/networking-config"
cp "/etc/network/interfaces" "$build_dir/networking-config"
if [ -e "/etc/wpa_supplicant/wpa_supplicant.conf" ]; then
  cp "/etc/wpa_supplicant/wpa_supplicant.conf" "$build_dir/networking-config"
fi

archive="/tmp/$today-logs.tar.gz"
cd "/tmp"
tar -zcf "$archive" "$today-logs"
