#!/bin/bash

kernel_version="4.14"
dev_tree_src="/opt/source/dtb-$kernel_version-ti"
sudo sed -i "206s/peripheral/host/" "$dev_tree_src/src/arm/am335x-bone-common.dtsi"
cd "$dev_tree_src"
sudo make clean
sudo make
sudo make install
sudo reboot
