#!/bin/bash

# usb_fwd -- Enable internet on a Beaglebone over USB with request forwarding.

set -e
source "$(git rev-parse --show-toplevel)/DevOps/frankfurter/scripts/tools/env"
host_ip=192.168.7.1
ip_fwd=/proc/sys/net/ipv4/ip_forward

usage="Enable internet on a Beaglebone with request forwarding.\n"
usage=$usage"Usage: $(basename $0) [-hHc] [command]\n\n"
usage=$usage"Options:\n"
usage=$usage$indent"-h    Show this help message.\n"
usage=$usage$indent"-i    Accept requests from this network interface "
usage=$usage"(required for the 'enable' command, ignored otherwise).\n"
usage=$usage$indent"-o    Forward requests to this network interface (required for 'enable').\n\n"
usage=$usage"Commands: enable, disable\n\n"
usage=$usage"Use 'ifconfig' to identify interface names.\n"
usage=$usage$warning"May require sudo to write to '$ip_fwd'."$clear

command="${@: -1}"
iface=""
oface=""
while getopts ":hi:o:" opt; do
  case $opt in
    h)
      echo -e "$usage" >&2
      exit
      ;;
    i) iface="$OPTARG";;
    o) oface="$OPTARG";;
    \?)
      echo -e $error"Invalid option: '-$OPTARG'"$clear >&2
      echo -e "Use '-h' to see usage." >&2
      exit 1
      ;;
  esac
done

if [[ "$command" = "enable" && ( -z "$iface" || -z "$oface" ) ]]; then
  echo -e $error"The 'enable' command requires both output and input network interfaces."$clear >&2
  echo -e "Use '-h' to see usage." >&2
  exit 1
fi

case $command in
  enable)
    ssh -t $ssh_options "$user@$default_ip" "sudo /sbin/route add default gw $host_ip"
    iptables --table nat --append POSTROUTING --out-interface "$oface" -j MASQUERADE
    iptables --append FORWARD --in-interface "$iface" -j ACCEPT
    echo 1 > "$ip_fwd"
    echo -e $success"Forwarding enabled."$clear
    ;;
  disable)
    ssh -t $ssh_options "$user@$default_ip" "sudo /sbin/route delete default gw $host_ip"
    # TODO: undo `iptables` modification on host
    echo 0 > "$ip_fwd"
    echo -e $success"Forwarding disabled."$clear
    ;;
  \?)
    echo -e $error"Invalid command: '$command'"$clear >&2
    echo -e "Use '-h' to see usage." >&2
    exit 1
esac
