---
# No need to update the default 'pi' user password from 'raspberry', since we
# want to help staff debug student robots.
- name: provision raspberry pi
  hosts: all
  roles:
    - role: base
    - role: raspbian
  vars:
    ansible_user: pi
    ansible_password: raspberry
    ansible_python_interpreter: python3
