CYAN = "\e[1;36m"
CLEAR = "\e[0m"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.hostname = "anvil"
  config.ssh.forward_agent = true

  desktop_mode = ENV['DESKTOP'] == 'yes'

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "1024"

    # Only needed for the desktop.
    if desktop_mode then
      vb.gui = true
      vb.customize ["modifyvm", :id, "--vram", "16"]
    end
  end

  private_ip = ENV['PRIVATE_IP']
  config.vm.network("private_network", ip: private_ip) unless private_ip.nil?

  forwarded_ports = ENV['FORWARDED_PORTS']
  if !forwarded_ports.nil? then
    forwarded_ports.split(',').each do |port|
      config.vm.network "forwarded_port", guest: port, host: port
    end
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "anvil.yml"
    ansible.extra_vars = {}
    name, email = ENV['NAME'], ENV['EMAIL']
    if !name.nil? and !email.nil? then
      ansible.extra_vars[:user] = {
        name: name,
        email: email,
      }
    end

    # TODO: add desktop tag if desktop_mode
  end

  if ENV['MOUNT_SYNCED'] != 'no' then
    config.vm.synced_folder("../..", "/home/vagrant/PieCentral", type: "virtualbox")
  end

  config.trigger.after :provision do |trigger|
    trigger.info = "#{CYAN}Anvil setup completed successfully!#{CLEAR}\n"
    trigger.info += "#{CYAN}Please copy the SSH key below (starts with 'ssh-rsa') and follow these instructions:#{CLEAR}\n"
    trigger.info += "#{CYAN}  https://help.github.com/en/articles/adding-a-new-ssh-key-to-your-github-account#{CLEAR}\n"
    trigger.run_remote = {
      inline: "cat .ssh/id_rsa.pub"
    }
  end
end
