# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fieldcontrol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='fieldcontrol.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x66ieldcontrol.proto\"\xfc\x01\n\x12\x46ieldControlToDawn\x12\x31\n\nteam_color\x18\x01 \x01(\x0e\x32\x1d.FieldControlToDawn.TeamColor\x12\x42\n\x13student_code_status\x18\x02 \x01(\x0e\x32%.FieldControlToDawn.StudentCodeStatus\")\n\tTeamColor\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04\x42LUE\x10\x01\x12\x08\n\x04GOLD\x10\x02\"D\n\x11StudentCodeStatus\x12\x08\n\x04IDLE\x10\x00\x12\n\n\x06TELEOP\x10\x01\x12\x0e\n\nAUTONOMOUS\x10\x02\x12\t\n\x05\x45STOP\x10\x03\"\x9a\x01\n\x12\x44\x61wnToFieldControl\x12\x33\n\x0b\x64\x61wn_status\x18\x01 \x01(\x0e\x32\x1e.DawnToFieldControl.DawnStatus\"O\n\nDawnStatus\x12\x16\n\x12STUDENT_DISCONNECT\x10\x00\x12\x08\n\x04IDLE\x10\x01\x12\n\n\x06TELEOP\x10\x02\x12\x08\n\x04\x41UTO\x10\x03\x12\t\n\x05\x45STOP\x10\x04\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_FIELDCONTROLTODAWN_TEAMCOLOR = _descriptor.EnumDescriptor(
  name='TeamColor',
  full_name='FieldControlToDawn.TeamColor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOLD', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=164,
  serialized_end=205,
)
_sym_db.RegisterEnumDescriptor(_FIELDCONTROLTODAWN_TEAMCOLOR)

_FIELDCONTROLTODAWN_STUDENTCODESTATUS = _descriptor.EnumDescriptor(
  name='StudentCodeStatus',
  full_name='FieldControlToDawn.StudentCodeStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TELEOP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTONOMOUS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ESTOP', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=207,
  serialized_end=275,
)
_sym_db.RegisterEnumDescriptor(_FIELDCONTROLTODAWN_STUDENTCODESTATUS)

_DAWNTOFIELDCONTROL_DAWNSTATUS = _descriptor.EnumDescriptor(
  name='DawnStatus',
  full_name='DawnToFieldControl.DawnStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STUDENT_DISCONNECT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TELEOP', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTO', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ESTOP', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=353,
  serialized_end=432,
)
_sym_db.RegisterEnumDescriptor(_DAWNTOFIELDCONTROL_DAWNSTATUS)


_FIELDCONTROLTODAWN = _descriptor.Descriptor(
  name='FieldControlToDawn',
  full_name='FieldControlToDawn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team_color', full_name='FieldControlToDawn.team_color', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='student_code_status', full_name='FieldControlToDawn.student_code_status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FIELDCONTROLTODAWN_TEAMCOLOR,
    _FIELDCONTROLTODAWN_STUDENTCODESTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=275,
)


_DAWNTOFIELDCONTROL = _descriptor.Descriptor(
  name='DawnToFieldControl',
  full_name='DawnToFieldControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dawn_status', full_name='DawnToFieldControl.dawn_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DAWNTOFIELDCONTROL_DAWNSTATUS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=432,
)

_FIELDCONTROLTODAWN.fields_by_name['team_color'].enum_type = _FIELDCONTROLTODAWN_TEAMCOLOR
_FIELDCONTROLTODAWN.fields_by_name['student_code_status'].enum_type = _FIELDCONTROLTODAWN_STUDENTCODESTATUS
_FIELDCONTROLTODAWN_TEAMCOLOR.containing_type = _FIELDCONTROLTODAWN
_FIELDCONTROLTODAWN_STUDENTCODESTATUS.containing_type = _FIELDCONTROLTODAWN
_DAWNTOFIELDCONTROL.fields_by_name['dawn_status'].enum_type = _DAWNTOFIELDCONTROL_DAWNSTATUS
_DAWNTOFIELDCONTROL_DAWNSTATUS.containing_type = _DAWNTOFIELDCONTROL
DESCRIPTOR.message_types_by_name['FieldControlToDawn'] = _FIELDCONTROLTODAWN
DESCRIPTOR.message_types_by_name['DawnToFieldControl'] = _DAWNTOFIELDCONTROL

FieldControlToDawn = _reflection.GeneratedProtocolMessageType('FieldControlToDawn', (_message.Message,), dict(
  DESCRIPTOR = _FIELDCONTROLTODAWN,
  __module__ = 'fieldcontrol_pb2'
  # @@protoc_insertion_point(class_scope:FieldControlToDawn)
  ))
_sym_db.RegisterMessage(FieldControlToDawn)

DawnToFieldControl = _reflection.GeneratedProtocolMessageType('DawnToFieldControl', (_message.Message,), dict(
  DESCRIPTOR = _DAWNTOFIELDCONTROL,
  __module__ = 'fieldcontrol_pb2'
  # @@protoc_insertion_point(class_scope:DawnToFieldControl)
  ))
_sym_db.RegisterMessage(DawnToFieldControl)


# @@protoc_insertion_point(module_scope)
