.PHONY: install artifacts-install lint test artificats

install:
	pip3 install pipenv
	pipenv install --dev
	./installlcm

artifacts-install:
	$(nop)

lint:
	pylint *.py

test:
	$(nop)

artifacts:
	$(nop)
