#!/bin/bash

# bootstrap -- Raspberry Pi-side script that bootstraps the installation process.
#
# Runs interactively within an SSH client.
# Designed to exit quickly so that setup is largely autonomous.

# Enable passwordless sudo for the default user
echo "$USER ALL=(ALL) NOPASSWD:ALL" | sudo tee --append "/etc/sudoers.d/$USER"
sudo chmod 0440 "/etc/sudoers.d/$USER"

# Install installation service
mkdir -p "$HOME/.config/systemd/user"
mv "$HOME/install.service" "$HOME/.config/systemd/user"
systemctl --user daemon-reload && systemctl --user enable install.service

# Remove settings that cause network unavailability on boot
sudo sed -i "/auto eth0/d" /etc/network/interfaces
sudo sed -i "/iface eth0 inet dhcp/d" /etc/network/interfaces

# Add Google's DNS server
echo "nameserver 8.8.8.8" | sudo tee --append /etc/resolvconf/resolv.conf.d/head
echo "nameserver 8.8.4.4" | sudo tee --append /etc/resolvconf/resolv.conf.d/head

sudo reboot
