#!/bin/bash

# start_install -- Staff-run script to begin customizing an Ubuntu image for PiE.
#
# The Beaglebone must have internet access (e.g. through USB using `usb_net_fwd`).

source "$(git rev-parse --show-toplevel)/DevOps/frankfurter/scripts/tools/env"
echo "Starting frankfurter installation ..."
echo -e $warning"Remember to enable wifi on the Beaglebone with 'usb_net_fwd'."$clear

ssh-copy-id $ssh_options "$user@$default_ip" 2>/dev/null

echo "Copying scripts ..."
resources=(
    "$frankfurter/resources/interfaces"
    "$frankfurter/resources/update.sh"
    "$frankfurter/resources/install.service"
    "$frankfurter/resources/update.service"
    "$frankfurter/scripts/install/master_setup"
    "$frankfurter/scripts/install/bootstrap"
)
for resource in ${resources[@]}; do
    scp "$resource" "$user@$default_ip:~" 2> /dev/null
done

# Export Pipfiles into merged requirements.txt
echo "Building consolidated 'requirements.txt' ..."
requirements="$tmp_dir/requirements.txt"
make_requirements > "$requirements"
scp "$requirements" "$user@$default_ip:~" > /dev/null
rm "$requirements"

ssh -t $ssh_options "$user@$default_ip" "/home/$user/bootstrap" 2>/dev/null
echo -e $success"Installation process now entering autonomous mode."$clear
echo "Your Beaglebone should be ready in about 15 minutes."
echo
echo -e "You can verify your Beaglebone is ready by checking whether the file '~/install-flags/completed' exists."
echo -e $warning"The Beaglebone may periodically reboot during installation."$clear
