#!/bin/bash

# deploy_update -- Deploy an update manually over SCP/SSH rather than Dawn.

source "$(git rev-parse --show-toplevel)/DevOps/frankfurter/scripts/tools/env"
if ! ls "$frankfurter/build/frankfurter-update-"* 1> /dev/null 2>&1; then
    create_update -p
fi

scp "$frankfurter/build/"* "$user@$default_ip:~/updates"
ssh $ssh_options -t "$user@$default_ip" "/home/$user/bin/update.sh && sudo systemctl restart runtime.service"
