#ifndef UI_H
#define UI_H

// function prototypes
void manual_ui();

//A space for constants.
extern float pwmInput; //Value that is received from hibike and is the goal PWM
extern float pwmPID; //Value that is generated by PID, if PID is disabled, this will be equal to pwmInput
extern float pwmOutput; //Value controlled by current limiting and is what is written to the motor
extern float current_threshold; //threshold in amps
extern volatile signed long old_encoder0Pos;
extern double pos; //this used to be volatile.  Changed to not be float, so it'd compile.
extern double vel;
extern uint8_t driveMode; //0 for manual, 1 for PID Velocity, 2 for PID Position
extern bool hibike;
extern bool continualPrint;
extern unsigned long heartbeat;
extern unsigned long heartbeatLimit;
extern float PIDPos;
extern float PIDPosKP;
extern float PIDPosKI;
extern float PIDPosKD;

extern float PIDVel;
extern float PIDVelKP;
extern float PIDVelKI;
extern float PIDVelKD;


#endif /* UI_H */
