#ifndef UI_H
#define UI_H

// function prototypes
void manual_ui();

//A space for constants.
extern double pwmInput; //Value that is received from hibike and is the goal PWM
extern double pwmPID; //Value that is generated by PID, if PID is disabled, this will be equal to pwmInput
extern float pwmOutput; //Value controlled by current limiting and is what is written to the motor
extern float current_threshold; //threshold in amps
extern volatile signed long old_encoder0Pos;
extern double pos; //this used to be volatile.  Changed to not be double, so it'd compile.
extern double vel;
extern int driveMode; //0 for manual, 1 for PID Velocity, 2 for PID Position
extern bool hibike;
extern bool continualPrint;
extern unsigned long heartbeat;
extern unsigned long heartbeatLimit;
extern double PIDPos;
extern double PIDPosKP;
extern double PIDPosKI;
extern double PIDPosKD;

extern double PIDVel;
extern double PIDVelKP;
extern double PIDVelKI;
extern double PIDVelKD;


#endif /* UI_H */
