#ifndef DEVICES_H
#define DEVICES_H

typedef enum {
  LIMIT_SWITCH = 0x00,
  LINE_FOLLOWER = 0x01,
  POTENTIOMETER = 0x02,
  BATTERY_BUZZER = 0x04,
  TEAM_FLAG = 0x05,
  YOGI_BEAR = 0x0A,
  RFID = 0x0B,
  SERVO_CONTROL = 0x07,
  COLOR_SENSOR = 0x09,
  DISTANCE_SENSOR = 0x10,
  METAL_DETECTOR = 0x11,
  EXAMPLE_DEVICE = 0xFFFF
} deviceID;


#endif /* DEVICES_H */
