# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ansible.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ansible.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ransible.proto\"\x96\x03\n\x08\x44\x61wnData\x12\x38\n\x13student_code_status\x18\x01 \x01(\x0e\x32\x1b.DawnData.StudentCodeStatus\x12#\n\x08gamepads\x18\x02 \x03(\x0b\x32\x11.DawnData.Gamepad\x12\x18\n\x10peripheral_names\x18\x03 \x03(\t\x12\'\n\nteam_color\x18\x04 \x01(\x0e\x32\x13.DawnData.TeamColor\x12$\n\x08gamecode\x18\x05 \x01(\x0b\x32\x12.DawnData.Gamecode\x1a\x37\n\x07Gamepad\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04\x61xes\x18\x02 \x03(\x01\x12\x0f\n\x07\x62uttons\x18\x03 \x03(\x08\x1a\x18\n\x08Gamecode\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"D\n\x11StudentCodeStatus\x12\x08\n\x04IDLE\x10\x00\x12\n\n\x06TELEOP\x10\x01\x12\x0e\n\nAUTONOMOUS\x10\x02\x12\t\n\x05\x45STOP\x10\x03\")\n\tTeamColor\x12\x08\n\x04NONE\x10\x00\x12\x08\n\x04\x42LUE\x10\x01\x12\x08\n\x04GOLD\x10\x02\x62\x06proto3'
)



_DAWNDATA_STUDENTCODESTATUS = _descriptor.EnumDescriptor(
  name='StudentCodeStatus',
  full_name='DawnData.StudentCodeStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TELEOP', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTONOMOUS', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ESTOP', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=313,
  serialized_end=381,
)
_sym_db.RegisterEnumDescriptor(_DAWNDATA_STUDENTCODESTATUS)

_DAWNDATA_TEAMCOLOR = _descriptor.EnumDescriptor(
  name='TeamColor',
  full_name='DawnData.TeamColor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLUE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOLD', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=383,
  serialized_end=424,
)
_sym_db.RegisterEnumDescriptor(_DAWNDATA_TEAMCOLOR)


_DAWNDATA_GAMEPAD = _descriptor.Descriptor(
  name='Gamepad',
  full_name='DawnData.Gamepad',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='DawnData.Gamepad.index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axes', full_name='DawnData.Gamepad.axes', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buttons', full_name='DawnData.Gamepad.buttons', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=285,
)

_DAWNDATA_GAMECODE = _descriptor.Descriptor(
  name='Gamecode',
  full_name='DawnData.Gamecode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='DawnData.Gamecode.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=311,
)

_DAWNDATA = _descriptor.Descriptor(
  name='DawnData',
  full_name='DawnData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='student_code_status', full_name='DawnData.student_code_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamepads', full_name='DawnData.gamepads', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='peripheral_names', full_name='DawnData.peripheral_names', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='team_color', full_name='DawnData.team_color', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gamecode', full_name='DawnData.gamecode', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DAWNDATA_GAMEPAD, _DAWNDATA_GAMECODE, ],
  enum_types=[
    _DAWNDATA_STUDENTCODESTATUS,
    _DAWNDATA_TEAMCOLOR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=424,
)

_DAWNDATA_GAMEPAD.containing_type = _DAWNDATA
_DAWNDATA_GAMECODE.containing_type = _DAWNDATA
_DAWNDATA.fields_by_name['student_code_status'].enum_type = _DAWNDATA_STUDENTCODESTATUS
_DAWNDATA.fields_by_name['gamepads'].message_type = _DAWNDATA_GAMEPAD
_DAWNDATA.fields_by_name['team_color'].enum_type = _DAWNDATA_TEAMCOLOR
_DAWNDATA.fields_by_name['gamecode'].message_type = _DAWNDATA_GAMECODE
_DAWNDATA_STUDENTCODESTATUS.containing_type = _DAWNDATA
_DAWNDATA_TEAMCOLOR.containing_type = _DAWNDATA
DESCRIPTOR.message_types_by_name['DawnData'] = _DAWNDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DawnData = _reflection.GeneratedProtocolMessageType('DawnData', (_message.Message,), {

  'Gamepad' : _reflection.GeneratedProtocolMessageType('Gamepad', (_message.Message,), {
    'DESCRIPTOR' : _DAWNDATA_GAMEPAD,
    '__module__' : 'ansible_pb2'
    # @@protoc_insertion_point(class_scope:DawnData.Gamepad)
    })
  ,

  'Gamecode' : _reflection.GeneratedProtocolMessageType('Gamecode', (_message.Message,), {
    'DESCRIPTOR' : _DAWNDATA_GAMECODE,
    '__module__' : 'ansible_pb2'
    # @@protoc_insertion_point(class_scope:DawnData.Gamecode)
    })
  ,
  'DESCRIPTOR' : _DAWNDATA,
  '__module__' : 'ansible_pb2'
  # @@protoc_insertion_point(class_scope:DawnData)
  })
_sym_db.RegisterMessage(DawnData)
_sym_db.RegisterMessage(DawnData.Gamepad)
_sym_db.RegisterMessage(DawnData.Gamecode)


# @@protoc_insertion_point(module_scope)
