if [[ $- != *i* ]] ; then
  # Shell is non-interactive, so no need to do anything
  return
fi

# TODO(vincent): fix and uncomment the line below once we know where dawn is installed
# alias dawn='sudo startxiwi -n trusty /opt/dawn/etc'
alias term='sudo enter-chroot'
alias ubuntu='sudo startunity -X xorg'
