# Runtime Configuration

services:
  broker:
    sockets:
      fieldcontrol:
        socket_type: sub
        address: tcp://127.0.0.1:6002
        bind: true
      journal_in:
        socket_type: sub
        address: ipc:///tmp/journal.sock
        bind: true
      journal_out:
        socket_type: pub
        address: tcp://127.0.0.1:6003
        bind: true
    proxies:
      journal:
        frontend: journal_in
        backend: journal_out
    config: {}  # TODO: remove
  executor:
    sockets:
      journal:
        socket_type: pub
        address: ipc:///tmp/journal.sock
        send_timeout: 5
      device:
        socket_type: sub
        address: ipc:///tmp/device.sock
    config:
      execution_period: 0.05  # 20 Hz
      device_schema: config/devices.yaml
      dawn:
        recv_host: 127.0.0.1
        recv_port: 6000
        send_port: 6001
  device:
    sockets:
      journal:
        socket_type: pub
        address: ipc:///tmp/journal.sock
        send_timeout: 5
      device:
        socket_type: pub
        address: ipc:///tmp/device.sock
        bind: true
    config:
      device_schema: config/devices.yaml
      max_devices: 20
