# Runtime Configuration

services:
  broker:
    sockets:
      fieldcontrol:
        socket_type: sub
        address: tcp://127.0.0.1:6000
      journal_in:
        socket_type: sub
        address: unix:///tmp/journal.sock
      journal_out:
        socket_type: pub
        address: tcp://127.0.0.1:6010
    proxies:
      journal:
        frontend: journal_in
        backend: journal_out

  # executor:
  #   sockets:
  #     journal:
  #       type: pub
  #       connect: unix:///tmp/journal.sock
  #
  # device:
  #   sockets:
  #     journal:
  #       type: pub
  #       connect: unix:///tmp/journal.sock
