# Runtime Configuration

services:
  broker:
    sockets:
      fieldcontrol:
        socket_type: sub
        address: tcp://127.0.0.1:6000
      journal_in:
        socket_type: sub
        address: ipc:///tmp/journal.sock
      journal_out:
        socket_type: pub
        address: tcp://127.0.0.1:6010
    proxies:
      journal:
        frontend: journal_in
        backend: journal_out

  executor:
    sockets:
      journal:
        socket_type: pub
        address: ipc:///tmp/journal.sock

  device:
    sockets:
      journal:
        socket_type: pub
        address: ipc:///tmp/journal.sock
