# runtime/config/devices.yaml

smartsensor:
  LimitSwitch:
    type_id: 0
    delay: 0.04
    params:
      - name: switch0
        type: bool
        subscribed: true
      - name: switch1
        type: bool
        subscribed: true
      - name: switch2
        type: bool
        subscribed: true
  LineFollower:
    type_id: 1
    delay: 0.04
    params:
      - name: left
        type: bool
        subscribed: true
      - name: center
        type: bool
        subscribed: true
      - name: right
        type: bool
        subscribed: true
  Potentiometer:
    type_id: 2
    delay: 0.04
    params:
      - name: pot0
        type: float
        subscribed: true
      - name: pot1
        type: float
        subscribed: true
      - name: pot2
        type: float
        subscribed: true
  Encoder:
    type_id: 3
    delay: 0.04
    params:
      - name: rotation
        type: int16
  BatteryBuzzer:
    type_id: 4
    delay: 0.04
    params:
      - name: is_unsafe
        type: bool
        subscribed: true
      - name: calibrated
        type: bool
      - name: v_cell1
        type: float
      - name: v_cell2
        type: float
      - name: v_cell3
        type: float
      - name: v_batt
        type: float
        subscribed: true
      - name: dv_cell2
        type: float
      - name: dv_cell3
        type: float
  TeamFlag:
    type_id: 5
    delay: 0.04
    params:
      - name: mode
        type: bool
        writeable: true
      - name: blue
        type: bool
        writeable: true
      - name: yellow
        type: bool
        writeable: true
      - name: led1
        type: bool
        writeable: true
      - name: led2
        type: bool
        writeable: true
      - name: led3
        type: bool
        writeable: true
      - name: led4
        type: bool
        writeable: true
  ServoControl:
    type_id: 7
    delay: 0.04
    params:
      - name: servo0
        type: float
        writeable: true
        lower: -1.0
        upper: 1.0
        subscribed: true
      - name: servo1
        type: float
        writeable: true
        lower: -1.0
        upper: 1.0
        subscribed: true
  YogiBear:
    type_id: 10
    delay: 0.04
    params:
      - name: duty_cycle
        type: float
        writeable: true
        lower: -1.0
        upper: 1.0
        subscribed: true
      - name: pid_pos_setpoint
        type: float
        readable: false
        writeable: true
      - name: pid_pos_kp
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_pos_ki
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_pos_kd
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_vel_setpoint
        type: float
        readable: false
        writeable: true
      - name: pid_vel_kp
        type: float
        readable: false
        writeable: true
      - name: pid_vel_ki
        type: float
        readable: false
        writeable: true
      - name: pid_vel_kd
        type: float
        readable: false
        writeable: true
      - name: current_thresh
        type: float
        readable: false
        writeable: true
        lower: 2.0
        upper: 10.0
      - name: enc_pos
        type: float
        writeable: true
        subscribed: true
      - name: enc_vel
        type: float
        subscribed: true
      - name: motor_current
        type: float
      - name: deadband
        type: float
        writeable: true
  RFID:
    type_id: 11
    delay: 0.04
    params:
      - name: id
        type: uint32
        subscribed: true
      - name: tag_detect
        type: uint8
        subscribed: true
  PolarBear:
    type_id: 12
    delay: 0.04
    params:
      - name: duty_cycle
        type: float
        writeable: true
        lower: -1.0
        upper: 1.0
        subscribed: true
      - name: pid_pos_setpoint
        type: float
        readable: false
        writeable: true
      - name: pid_pos_kp
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_pos_ki
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_pos_kd
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_vel_setpoint
        type: float
        readable: false
        writeable: true
      - name: pid_vel_kp
        type: float
        readable: false
        writeable: true
      - name: pid_vel_ki
        type: float
        readable: false
        writeable: true
      - name: pid_vel_kd
        type: float
        readable: false
        writeable: true
      - name: current_thresh
        type: float
        readable: false
        writeable: true
        lower: 2.0
        upper: 10.0
      - name: enc_pos
        type: float
        writeable: true
        subscribed: true
      - name: enc_vel
        type: float
        subscribed: true
      - name: motor_current
        type: float
      - name: deadband
        type: float
        writeable: true
  KoalaBear:
    type_id: 13
    delay: 0.04
    params:
      - name: duty_cycle_a
        type: float
        writeable: true
        lower: -1.0
        upper: 1.0
        subscribed: true
      - name: pid_kp_a
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_ki_a
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_kd_a
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: enc_pos_a
        type: float
        writeable: true
        subscribed: true
      - name: deadband_a
        type: float
        writeable: true
      - name: motor_enabled_a
        type: bool
        writeable: true
        subscribed: true
      - name: drive_mode_a
        type: uint8
        writeable: true
      - name: duty_cycle_b
        type: float
        writeable: true
        lower: -1.0
        upper: 1.0
        subscribed: true
      - name: pid_kp_b
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_ki_b
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: pid_kd_b
        type: float
        readable: false
        writeable: true
        lower: 0.0
      - name: enc_pos_b
        type: float
        writeable: true
        subscribed: true
      - name: deadband_b
        type: float
        writeable: true
      - name: motor_enabled_b
        type: bool
        writeable: true
        subscribed: true
      - name: drive_mode_b
        type: uint8
        writeable: true

dawn:
  Gamepad:
    type_id: 14
    params:
      - name: button_a
        type: bool
      - name: button_b
        type: bool
      - name: button_x
        type: bool
      - name: button_y
        type: bool
      - name: l_bumper
        type: bool
      - name: r_bumper
        type: bool
      - name: l_trigger
        type: bool
      - name: r_trigger
        type: bool
      - name: button_back
        type: bool
      - name: button_start
        type: bool
      - name: l_stick
        type: bool
      - name: r_stick
        type: bool
      - name: dpad_up
        type: bool
      - name: dpad_down
        type: bool
      - name: dpad_left
        type: bool
      - name: dpad_right
        type: bool
      - name: button_xbox
        type: bool
      - name: joystick_left_x
        type: float
        lower: -1.0
        upper: 1.0
      - name: joystick_left_y
        type: float
        lower: -1.0
        upper: 1.0
      - name: joystick_right_x
        type: float
        lower: -1.0
        upper: 1.0
      - name: joystick_right_y
        type: float
        lower: -1.0
        upper: 1.0
