# Runtime service configuration

broker:
  replicas: 1
  sockets:
    datagram_recv:
      socket_type: dish
      address: udp://*:6000
      bind: true
    gamepad_status:
      socket_type: pub
      address: ipc:///tmp/gamepad-status.sock
      bind: true
    sensor_status:
      socket_type: sub
      address: ipc:///tmp/sensor-status.sock
  max_workers: 5

executor:
  replicas: 1
  daemon: false
  sockets:
    command:
      socket_type: rep
      address: tcp://*:6002
      bind: true
    device_status:
      socket_type: sub
      address:
        - ipc:///tmp/sensor-status.sock
        - ipc:///tmp/gamepad-status.sock
  student_code: runtime.game.studentcode
  device_aliases: config/device-aliases.yaml
  loop_interval: 0.05  # 20 Hz

device:
  replicas: 1
  sockets:
    sensor_status:
      socket_type: pub
      address: ipc:///tmp/sensor-status.sock
      bind: true
    sensor_command:
      socket_type: sub
      address: ipc:///tmp/sensor-command.sock
      bind: true
