# Runtime service configuration

broker:
  replicas: 1
  retry:
    - strategy: loop
      interval: 5
  sockets:
    journal_in:
      socket_type: sub
      address: ipc:///tmp/journal.sock
      bind: true
    journal_out:
      socket_type: pub
      address: tcp://127.0.0.1:6003
      bind: true
  max_workers: 5
  proxies:
    journal:
      frontend: journal_in
      backend: journal_out

executor:
  replicas: 1
  daemon: false
  retry:
    - strategy: loop
      interval: 5
  sockets:
    journal:
      socket_type: pub
      address: ipc:///tmp/journal.sock
      send_timeout: 5
    command:
      socket_type: rep
      address: tcp://127.0.0.1:6002
      bind: true
    device_event:
      socket_type: sub
      address: ipc:///tmp/device-event.sock
  student_code: runtime.game.studentcode
  device_aliases: config/device-aliases.yaml
  loop_interval: 1 # 0.05  # 20 Hz

device:
  replicas: 1
  retry:
    - strategy: loop
      interval: 5
  sockets:
    journal:
      socket_type: pub
      address: ipc:///tmp/journal.sock
      send_timeout: 5
    device_event:
      socket_type: pub
      address: ipc:///tmp/device-event.sock
      bind: true
    device_command:
      socket_type: sub
      address: ipc:///tmp/device-command.sock
  baud_rate: 115200
  hotplug_max_events: 128
