# Runtime service configuration

broker:
  replicas: 1
  retry:
    - strategy: loop
      interval: 5
  sockets:
    journal_in:
      socket_type: sub
      address: ipc:///tmp/journal.sock
      bind: true
    journal_out:
      socket_type: pub
      address: tcp://127.0.0.1:6003
      bind: true
    datagram_recv:
      socket_type: dish
      address: udp://*:6000
      bind: true
    gamepad_event:
      socket_type: pub
      address: ipc:///tmp/gamepad-event.sock
      bind: true
    sensor_event:
      socket_type: sub
      address: ipc:///tmp/sensor-event.sock
  max_workers: 5
  proxies:
    journal:
      frontend: journal_in
      backend: journal_out

executor:
  replicas: 1
  daemon: false
  retry:
    - strategy: loop
      interval: 5
  sockets:
    journal:
      socket_type: pub
      address: ipc:///tmp/journal.sock
      send_timeout: 5
    command:
      socket_type: rep
      address: tcp://127.0.0.1:6002
      bind: true
    device_event:
      socket_type: sub
      address:
        - ipc:///tmp/gamepad-event.sock
        - ipc:///tmp/sensor-event.sock
      # bind: true
  student_code: runtime.game.studentcode
  device_aliases: config/device-aliases.yaml
  loop_interval: 0.05  # 20 Hz

device:
  replicas: 1
  retry:
    - strategy: loop
      interval: 5
  sockets:
    journal:
      socket_type: pub
      address: ipc:///tmp/journal.sock
      send_timeout: 5
    sensor_event:
      socket_type: pub
      address: ipc:///tmp/sensor-event.sock
      bind: true
    sensor_command:
      socket_type: sub
      address: ipc:///tmp/sensor-command.sock
      bind: true
  baud_rate: 115200
  hotplug_max_events: 128
